### PR TITLE
Switch to newer call that doesn't wrap values

### PR DESCRIPTION
**Pull request by DarkWiiPlayer**
As recommended in the [documentation of the binary protocol](https://www.tarantool.io/en/doc/2.2/dev_guide/internals/box_protocol/), this newer version of the call request doesn't wrap individual return values (reducing both table allocations and developer frustration) as described in #7

### CODE REVIEW

**Comment by amdei** [comment]
Will it break all existing code behaviour?

**Comment by DarkWiiPlayer** [comment]
Most likely, yes. Fixing that should be easy, but might be tedious for larger projects. If that's too much of a problem, I can make a new pull request defining a different new function for the newer method.

**Comment by perusio** [comment]
Can you please do that @DarkWiiPlayer. It would be highly appreciated. Thank you.

**Comment by DarkWiiPlayer** [comment]
I'm closing this PR then; creating a new one in a second :)

**Pull request closed without merging**
